extensions:
  basicauth/client:
    client_auth:
      username: "${SPLUNK_ENT_CRED}"
      password: "${SPLUNK_ENT_PASS}"
receivers:
  prometheus/internal:
    config:
      scrape_configs:
        - job_name: self
          scrape_interval: 60s
          static_configs:
            - targets: [ localhost:8888 ]
  splunkenterprise:
    auth: 
      authenticator: basicauth/client
    tls:
      insecure_skip_verify: true
    endpoint: "${SPLUNK_ENT_PATH}"
    collection_interval: 60s
    timeout: 15s
    metrics:
      splunk.license.index.usage:
        enabled: true
      splunk.indexer.throughput:
        enabled: true

processors:
  batch:
  resourcedetection:
    detectors: [system, env]
    timeout: 2s
    override: true
exporters:
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: "https://api.${SPLUNK_REALM}.signalfx.com"
    ingest_url: https://ingest.${SPLUNK_REALM}.signalfx.com
    sync_host_metadata: true

service:
  extensions: 
    - basicauth/client
  pipelines:
    metrics:
      receivers:
      - splunkenterprise
      - prometheus/internal
      processors:
      - batch
      - resourcedetection
      exporters:
      - signalfx 
  telemetry:
    metrics:
      address: localhost:8888
