receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
  prometheus/internal:
    config:
      scrape_configs:
        - job_name: self
          scrape_interval: 60s
          static_configs:
            - targets: [ localhost:8888 ]

processors:
  batch:
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: true
exporters:
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: "https://api.${SPLUNK_REALM}.signalfx.com"
    ingest_url: https://ingest.${SPLUNK_REALM}.signalfx.com
    sync_host_metadata: true
    local_meta_file: /tmp/meta.yaml

service:
  pipelines:
    metrics:
      receivers:
      - otlp
      - prometheus/internal
      processors:
      - batch
      - resourcedetection
      exporters:
      - signalfx 
  telemetry:
    metrics:
      address: localhost:8888
